#!/bin/bash

/opt/euler/eye --yap --nope ReificationsArchitectureOntology.ttl UpperArchitectureOntology.ttl ControlledArchitectureVocabularies.ttl rules/*.n3 --query queries/ExtractOntology.n3 | ./fixbools > inferred/ArchitectureOntologyInferred.ttl
