#!/bin/bash

/opt/euler/eye --yap --nope ReificationsArchitectureOntology.ttl UpperArchitectureOntology.ttl /opt/euler/rdfs-subClassOf.n3 --pass | ./fixbools > inferred/ArchitectureOntologyInferredFixed.ttl
